 target-version = "py311"
 [lint]
 preview = true
select = [
    "A",     # flake8-buildins
    "ANN",   # flake8-annotations
    "ARG",   # flake8-unused-arguments
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "COM",   # flake8-commas
    "D",     # pydocstyle
    "DOC",   # pydoclint
    "E",     # pycodestyle - errors
    "ERA",   # eradicate
    "F",     # pyflakes
    "FA",    # flake8-funny-annotations
    "FIX",   # flake8-fixme
    "FLY",   # flake8-flynt
    "FURB",  # refurb
    "I",     # isort
    "ISC",   # flake8-implicit-str-concat
    "ICN",   # flake8-import-conventions
    "INP",   # flake8-no-pep420
    "N",     # pep8-naming
    "NPY",   # numpy-specific rules
    "PD",    # pandas-vet
    "PERF",  # perflint
    "PGH",   # pygrep-hook
    "PIE",   # flake8-pie
    "PL",    # pylint
    "PTH",   # flake8-use-pathlib
    "PYI",   # flake8-pyi
    "Q",     # flake8-quotes
    "RET",   # flake8-return
    "RUF",   # ruff specific rules
    "S",     # flake8-bandit
    "SIM",   # flake8-simplify
    "SLF",   # flake8-self
    "TC",    # flake8-type-checking
    "TD",    # flake8-todo
    "T10",   # flake8-debugger
    "T20",   # flake8-print
    "TID",   # flake8-tidy-imports
    "UP",    # pyupgrade
    "W",     # pycodestyle - warnings
]
ignore = [
    "ANN401",  #  Allow  typing.Any
    "ANN204",  #  Missing return type annotation for special method
    "D203", # 1 blank line required before class docstring
    "D213", # blank-line-before-class-docstring
    "PLR0913", # too-many-arguments
    "PGH003",  # Blanket type ignore for types
    "PLW2901", # Redefined loop variable
    "PLR6301", # could be a function, class method, or static method (does not respect inheritance)
    "S311",  #  suspicious-non-cryptographic-random-usage
]
 pylint = {max-positional-args=10 }
 [lint.per-file-ignores]
 "*.ipynb" = [
     "PLE1142",
     "F704",
     "T201"
 ]
 "test_*" = [
     "S101",
     "S404",
     "S603",
     "S607"
 ]
