name: Code-Analysis

on: [push]

jobs:
  test_basis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run unit-tests
        run: |
          python -m unittest discover -v -s tests -t .

  test_chemprop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install torch
          pip install .[chemprop]
      - name: Run unit-tests for chemprop
        run: |
          python -m unittest discover -v -s test_extras/test_chemprop -t .

  test_notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .[notebooks]
      - name: Run unit-tests for notebooks
        run: |
          python test_extras/test_notebooks/test_notebooks.py  --continue-on-failure
